[project]
authors = ["Tal Ashuach <tal.ashuach@insitro.com>", "Ethan Weinberger <ewein@cs.washington.edu>"]
channels = ["pytorch", "nvidia", "conda-forge", "bioconda"]
description = "Contrastive Variational Inference+"
name = "ContrastiveVI+"
platforms = ["osx-64", "linux-64"]
version = "0.1.0"
license-file = "LICENSE.md"

[tasks]

[dependencies]
python = "3.10.*"
pytorch = ">=2.2.2,<3"
bioconductor-summarizedexperiment = ">=1.28.0,<2"
bioconductor-singlecellexperiment = ">=1.20.0,<2"
r-seurat = ">=5.1.0,<6"
r-mixtools = ">=2.0.0,<3"
r-presto = ">=1.0.0,<2"
anndata2ri = ">=1.3.2,<2"
scvi-tools = "==0.20.3"
itables = "==1.5.4"
adjusttext = ">=1.2.0,<2"
muon = ">=0.1.6,<0.2"
optax = "==0.2.0"
scipy = "==1.12.0"
requests = ">=2.32.3,<3"
boto3 = ">=1.35.52,<2"
scikit-misc = ">=0.1.4,<0.2"
